
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Date;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Saurabh Shubham
 */
public class checkout extends javax.swing.JFrame {

    /**
     * Creates new form checkout
     */
    public checkout() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        amountcheckout = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        nbn = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        rb1 = new javax.swing.JRadioButton();
        rb2 = new javax.swing.JRadioButton();
        rb3 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        pin = new javax.swing.JTextField();
        orderidcheckout = new javax.swing.JLabel();
        phonecheckout = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        usernamecheckout = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/logo.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(290, 50, 400, 90);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel2.setText("Coins you have to pay:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(12, 26, 182, 21);

        amountcheckout.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        amountcheckout.setForeground(new java.awt.Color(153, 51, 0));
        amountcheckout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/Coin-icon.png"))); // NOI18N
        amountcheckout.setText("0.00");
        jPanel1.add(amountcheckout);
        amountcheckout.setBounds(212, 26, 183, 30);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/2.jpg"))); // NOI18N
        jPanel1.add(jLabel9);
        jLabel9.setBounds(0, 0, 440, 80);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(70, 160, 440, 80);

        jPanel2.setLayout(null);

        nbn.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        nbn.setText("Order ID : ");
        jPanel2.add(nbn);
        nbn.setBounds(30, 30, 84, 21);

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel4.setText("Pin Code : ");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(20, 250, 88, 21);

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel5.setText("Phone Number:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(388, 31, 124, 21);

        ta.setColumns(20);
        ta.setRows(5);
        jScrollPane1.setViewportView(ta);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(136, 104, 210, 110);

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel6.setText("City: ");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(412, 112, 44, 21);

        buttonGroup1.add(rb1);
        rb1.setFont(new java.awt.Font("Tw Cen MT", 1, 15)); // NOI18N
        rb1.setText("Patna");

        buttonGroup1.add(rb2);
        rb2.setFont(new java.awt.Font("Tw Cen MT", 1, 15)); // NOI18N
        rb2.setText("Jaipur");

        buttonGroup1.add(rb3);
        rb3.setFont(new java.awt.Font("Tw Cen MT", 1, 15)); // NOI18N
        rb3.setText("Delhi");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rb1)
                    .addComponent(rb2)
                    .addComponent(rb3))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(rb1)
                .addGap(18, 18, 18)
                .addComponent(rb2)
                .addGap(18, 18, 18)
                .addComponent(rb3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3);
        jPanel3.setBounds(530, 112, 179, 140);

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel7.setText("Adderss :");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(30, 110, 74, 21);
        jPanel2.add(pin);
        pin.setBounds(136, 245, 215, 30);

        orderidcheckout.setBackground(new java.awt.Color(153, 255, 153));
        orderidcheckout.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        orderidcheckout.setForeground(new java.awt.Color(51, 0, 51));
        orderidcheckout.setText("Nothing");
        jPanel2.add(orderidcheckout);
        orderidcheckout.setBounds(140, 30, 215, 30);

        phonecheckout.setBackground(new java.awt.Color(153, 255, 153));
        phonecheckout.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        phonecheckout.setForeground(new java.awt.Color(51, 0, 51));
        jPanel2.add(phonecheckout);
        phonecheckout.setBounds(541, 31, 183, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/1.jpg"))); // NOI18N
        jPanel2.add(jLabel3);
        jLabel3.setBounds(0, 0, 760, 330);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(70, 280, 760, 330);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/place.png"))); // NOI18N
        jButton1.setText("Place Order");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(300, 640, 150, 40);

        usernamecheckout.setBackground(new java.awt.Color(51, 255, 0));
        usernamecheckout.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        usernamecheckout.setForeground(new java.awt.Color(255, 51, 102));
        usernamecheckout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usernamecheckout.setText("Guest");
        usernamecheckout.setToolTipText("");
        getContentPane().add(usernamecheckout);
        usernamecheckout.setBounds(699, 70, 200, 26);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/cancel.png"))); // NOI18N
        jButton2.setText("Cancel");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(490, 640, 150, 40);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/4.jpg"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 940, 710);

        setSize(new java.awt.Dimension(945, 748));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 double retrived_balance=0.0;
  String s="";
  
    try{
           if(!(rb1.isSelected() || rb2.isSelected() || rb3.isSelected()))
                 JOptionPane.showMessageDialog(null,"Please select your city");
           else
           {
            
            Class.forName("java.sql.Driver");
            String database = "jdbc:mysql://localhost:3306/foodforintelligents";
            Connection conn = DriverManager.getConnection(database, "root","");
            Statement stmt = conn.createStatement();
            String sql = "update menu set order_amount = " + amountcheckout.getText() + "where username = '" + usernamecheckout.getText() + "';";
            stmt.executeUpdate(sql);     
            
            sql = "select balance from menu where username = '" + usernamecheckout.getText() + "';" ;
             ResultSet rs = stmt.executeQuery(sql);
             if(rs.next())
             {
                 
                 s = rs.getString("balance");
                 retrived_balance = Double.parseDouble(s);
             }
             else
             {
                 System.out.println("Database Problem!!");
             }
            
             sql = "update menu set balance = " + (retrived_balance - Double.parseDouble(amountcheckout.getText())) + "where username = '" + usernamecheckout.getText() + "';";
             stmt.executeUpdate(sql);  
             Date date = new Date();
             String stringdate = date.toString();
             sql = "update menu set order_time = '" + stringdate + "' where username = '" + usernamecheckout.getText() + "';" ;
             stmt.executeUpdate(sql);
             sql = "update menu set purchaseid = '" + orderidcheckout.getText() + "' where username = '" + usernamecheckout.getText() + "';" ;
             stmt.executeUpdate(sql);
             menu m = new menu();
             //---------------------------------------------
             m.usernamemenu.setText(usernamecheckout.getText());
             
             sql = "select balance from menu where username = '" + usernamecheckout.getText() + "';" ;
             rs = stmt.executeQuery(sql);
             if(rs.next())
             {
                
                 s = rs.getString("balance");
             }
             m.balance.setText(s);
             JOptionPane.showMessageDialog(null,"Thank You for Placing the order.\n   You can expect the delivery in next 30 minutes. \n ** Check Order Status for more Details **");
             //---------------------------------------------
             
             m.setVisible(true);
             this.setVisible(false);
           }
              
          }
            catch(Exception e)
            {
               System.out.println("Not Connected, Error:  "+e.getMessage());
            }     
  
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

int selection = JOptionPane.showConfirmDialog (null, "Are you sure?","WARNING", JOptionPane.YES_NO_OPTION);   
if(selection==0)
{
    menu m = new menu();
    m.usernamemenu.setText(usernamecheckout.getText());
      try{
            Class.forName("java.sql.Driver");
            String database = "jdbc:mysql://localhost:3306/foodforintelligents";
            Connection conn = DriverManager.getConnection(database, "root","");
            Statement stmt = conn.createStatement();
             String sql = "select balance from menu where username = '" + usernamecheckout.getText() + "';" ;
             ResultSet rs = stmt.executeQuery(sql);
             if(rs.next())
             {
                 String s;
                 s = rs.getString("balance");
                 m.balance.setText(s);
             }
              
            }
            catch(Exception e)
            {
               System.out.println("Not Connected, Error:  "+e.getMessage());
            }
    
    m.setVisible(true);
    this.setVisible(false);
}else
{
    
}
// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(checkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(checkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(checkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(checkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new checkout().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel amountcheckout;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nbn;
    public static javax.swing.JLabel orderidcheckout;
    public static javax.swing.JLabel phonecheckout;
    private javax.swing.JTextField pin;
    private javax.swing.JRadioButton rb1;
    private javax.swing.JRadioButton rb2;
    private javax.swing.JRadioButton rb3;
    private javax.swing.JTextArea ta;
    public static javax.swing.JLabel usernamecheckout;
    // End of variables declaration//GEN-END:variables
}
