
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;




/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Saurabh Shubham
 */
public class feedback extends javax.swing.JFrame {

    /**
     * Creates new form feedback
     */
    public feedback() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ta = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        usernamefeedback = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        nbn = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        getContentPane().setLayout(null);

        ta.setBackground(new java.awt.Color(204, 204, 255));
        ta.setColumns(20);
        ta.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        ta.setRows(5);
        ta.setWrapStyleWord(true);
        jScrollPane1.setViewportView(ta);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(195, 219, 490, 250);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/ok.png"))); // NOI18N
        jButton1.setText("Submit");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(380, 490, 130, 40);

        usernamefeedback.setBackground(new java.awt.Color(51, 255, 0));
        usernamefeedback.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        usernamefeedback.setForeground(new java.awt.Color(255, 51, 102));
        usernamefeedback.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usernamefeedback.setText("Guest");
        usernamefeedback.setToolTipText("");
        getContentPane().add(usernamefeedback);
        usernamefeedback.setBounds(627, 67, 200, 26);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/logo.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(209, 38, 400, 94);

        nbn.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        nbn.setText("Your FeedBack:");
        getContentPane().add(nbn);
        nbn.setBounds(80, 180, 125, 21);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/2.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 860, 580);

        setSize(new java.awt.Dimension(867, 613));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     
  try{
            Class.forName("java.sql.Driver");
            String database = "jdbc:mysql://localhost:3306/foodforintelligents";
            Connection conn = DriverManager.getConnection(database, "root","");
            Statement stmt = conn.createStatement();
            String sql = "insert into feedback values('" + usernamefeedback.getText() + "','" + ta.getText() + "');";
            int i = stmt.executeUpdate(sql);
            System.out.println(""+i);
            
            if(i==1)
            {
                JOptionPane.showMessageDialog(null, "Thank You for the Feedback!!");
                menu m = new menu();
                m.usernamemenu.setText(usernamefeedback.getText());
                sql = "select balance from menu where username = '" + usernamefeedback.getText() + "';";
                ResultSet rs = stmt.executeQuery(sql);
                if(rs.next())
                {
                    String s = rs.getString("balance");
                    m.balance.setText(s);
                }
                m.setVisible(true);
                this.setVisible(false);
            }
            else
                System.out.println("Connection Error");
        }
        catch(Exception e)
         {
           System.out.println("Not Connected, Error:  "+e.getMessage());
         }        

// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(feedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(feedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(feedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(feedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new feedback().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nbn;
    private javax.swing.JTextArea ta;
    public static javax.swing.JLabel usernamefeedback;
    // End of variables declaration//GEN-END:variables
}
