
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Random;
import javax.swing.JOptionPane;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Saurabh Shubham
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        balance = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        usernamemenu = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        r1 = new javax.swing.JTextField();
        r2 = new javax.swing.JTextField();
        r3 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jButton15 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        s1 = new javax.swing.JTextField();
        s2 = new javax.swing.JTextField();
        s3 = new javax.swing.JTextField();
        s4 = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        o1 = new javax.swing.JTextField();
        o2 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/logo.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(510, 39, 474, 111);

        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel2.setText("Your Balance: ");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(12, 47, 93, 26);

        balance.setBackground(new java.awt.Color(51, 255, 0));
        balance.setFont(new java.awt.Font("Showcard Gothic", 0, 20)); // NOI18N
        balance.setForeground(new java.awt.Color(0, 102, 102));
        balance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/Coin-icon.png"))); // NOI18N
        jPanel2.add(balance);
        balance.setBounds(112, 47, 98, 26);

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/1.jpg"))); // NOI18N
        jPanel2.add(jLabel29);
        jLabel29.setBounds(0, 0, 230, 120);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(56, 53, 230, 120);

        jPanel3.setLayout(null);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/earncoin.png"))); // NOI18N
        jButton1.setText("Earn Coins");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(35, 88, 127, 42);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/profile.png"))); // NOI18N
        jButton2.setText("Your Profile");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);
        jButton2.setBounds(202, 52, 137, 44);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/feedback.png"))); // NOI18N
        jButton3.setText("FeedBack");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);
        jButton3.setBounds(202, 114, 137, 46);

        usernamemenu.setBackground(new java.awt.Color(51, 255, 0));
        usernamemenu.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        usernamemenu.setForeground(new java.awt.Color(0, 102, 102));
        usernamemenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usernamemenu.setText("Guest");
        usernamemenu.setToolTipText("");
        jPanel3.add(usernamemenu);
        usernamemenu.setBounds(12, 13, 336, 26);

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/1.jpg"))); // NOI18N
        jPanel3.add(jLabel30);
        jLabel30.setBounds(0, 0, 360, 180);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(1160, 40, 360, 180);

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel3.setLabelFor(jPanel4);
        jLabel3.setText("Regular: ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(25, 215, 72, 21);

        jPanel4.setLayout(null);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/front-1-1008x500.jpg"))); // NOI18N
        jPanel4.add(jLabel4);
        jLabel4.setBounds(930, 30, 260, 200);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/top-25-splendid-veg-pasta-reci.jpg"))); // NOI18N
        jPanel4.add(jLabel5);
        jLabel5.setBounds(500, 30, 260, 200);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/badam-pista-milkshake-2-glasse.jpg"))); // NOI18N
        jPanel4.add(jLabel6);
        jLabel6.setBounds(85, 25, 260, 200);

        r1.setEditable(false);
        r1.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        r1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        r1.setText("0");
        jPanel4.add(r1);
        r1.setBounds(50, 80, 30, 30);

        r2.setEditable(false);
        r2.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        r2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        r2.setText("0");
        jPanel4.add(r2);
        r2.setBounds(460, 70, 30, 30);

        r3.setEditable(false);
        r3.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        r3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        r3.setText("0");
        jPanel4.add(r3);
        r3.setBounds(890, 70, 30, 30);

        jButton5.setBackground(new java.awt.Color(255, 255, 153));
        jButton5.setFont(new java.awt.Font("Vivaldi", 1, 36)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 0, 0));
        jButton5.setText("Intelligent Shake");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton5);
        jButton5.setBounds(68, 243, 297, 53);

        jButton6.setBackground(new java.awt.Color(255, 255, 153));
        jButton6.setFont(new java.awt.Font("Vivaldi", 1, 36)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 0, 0));
        jButton6.setText("Intelligent Pizza");
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton6);
        jButton6.setBounds(920, 250, 283, 53);

        jButton7.setBackground(new java.awt.Color(255, 255, 153));
        jButton7.setFont(new java.awt.Font("Vivaldi", 1, 36)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 0, 0));
        jButton7.setText("Intelligent Pasta");
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton7);
        jButton7.setBounds(490, 240, 279, 53);

        jLabel16.setBackground(new java.awt.Color(51, 255, 0));
        jLabel16.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 0, 102));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/Coin-icon.png"))); // NOI18N
        jLabel16.setText("11.00");
        jPanel4.add(jLabel16);
        jLabel16.setBounds(12, 202, 61, 23);

        jLabel17.setBackground(new java.awt.Color(51, 255, 0));
        jLabel17.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 102, 102));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/Coin-icon.png"))); // NOI18N
        jLabel17.setText("15.00");
        jPanel4.add(jLabel17);
        jLabel17.setBounds(404, 192, 63, 23);

        jLabel19.setBackground(new java.awt.Color(51, 255, 0));
        jLabel19.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 204, 153));
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/Coin-icon.png"))); // NOI18N
        jLabel19.setText("19.99");
        jPanel4.add(jLabel19);
        jLabel19.setBounds(862, 200, 62, 23);

        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/plus.png"))); // NOI18N
        jButton15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton15);
        jButton15.setBounds(460, 30, 30, 30);

        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/minus.png"))); // NOI18N
        jButton17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton17);
        jButton17.setBounds(460, 110, 30, 30);

        jButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/plus.png"))); // NOI18N
        jButton18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton18);
        jButton18.setBounds(890, 30, 30, 30);

        jButton19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/minus.png"))); // NOI18N
        jButton19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton19);
        jButton19.setBounds(890, 110, 30, 30);

        jButton20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/plus.png"))); // NOI18N
        jButton20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton20);
        jButton20.setBounds(50, 40, 30, 30);

        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/minus.png"))); // NOI18N
        jButton16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton16);
        jButton16.setBounds(50, 120, 30, 30);

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/temp1.jpg"))); // NOI18N
        jPanel4.add(jLabel26);
        jLabel26.setBounds(0, 0, 1330, 330);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(20, 260, 1330, 330);

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel7.setText("Specials:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(25, 593, 71, 21);

        jPanel5.setLayout(null);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/rajbhog-sweet_24_.jpg"))); // NOI18N
        jPanel5.add(jLabel8);
        jLabel8.setBounds(1030, 30, 260, 200);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/gulab-jamun2.jpg"))); // NOI18N
        jPanel5.add(jLabel9);
        jLabel9.setBounds(380, 40, 260, 200);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/thai.jpg"))); // NOI18N
        jPanel5.add(jLabel10);
        jLabel10.setBounds(50, 40, 260, 200);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/jalebi-sweet-images-6.jpg"))); // NOI18N
        jPanel5.add(jLabel11);
        jLabel11.setBounds(710, 40, 235, 200);

        s1.setEditable(false);
        s1.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        s1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        s1.setText("0");
        jPanel5.add(s1);
        s1.setBounds(10, 80, 30, 30);

        s2.setEditable(false);
        s2.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        s2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        s2.setText("0");
        jPanel5.add(s2);
        s2.setBounds(340, 80, 30, 30);

        s3.setEditable(false);
        s3.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        s3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        s3.setText("0");
        jPanel5.add(s3);
        s3.setBounds(670, 80, 30, 30);

        s4.setEditable(false);
        s4.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        s4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        s4.setText("0");
        jPanel5.add(s4);
        s4.setBounds(990, 70, 30, 30);

        jButton9.setBackground(new java.awt.Color(255, 255, 153));
        jButton9.setFont(new java.awt.Font("Vivaldi", 1, 34)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 0, 0));
        jButton9.setText("Ghyal RajBhog");
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton9);
        jButton9.setBounds(1010, 270, 285, 50);

        jButton10.setBackground(new java.awt.Color(255, 255, 153));
        jButton10.setFont(new java.awt.Font("Vivaldi", 1, 34)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 0, 0));
        jButton10.setText("Thai - Tanic");
        jButton10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton10);
        jButton10.setBounds(70, 280, 215, 40);

        jButton11.setBackground(new java.awt.Color(255, 255, 153));
        jButton11.setFont(new java.awt.Font("Vivaldi", 1, 34)); // NOI18N
        jButton11.setForeground(new java.awt.Color(255, 0, 0));
        jButton11.setText("Lord of Rings");
        jButton11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton11);
        jButton11.setBounds(710, 280, 235, 50);

        jButton12.setBackground(new java.awt.Color(255, 255, 153));
        jButton12.setFont(new java.awt.Font("Vivaldi", 1, 27)); // NOI18N
        jButton12.setForeground(new java.awt.Color(255, 0, 0));
        jButton12.setText("Sudh Desi GulabJamun");
        jButton12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton12);
        jButton12.setBounds(350, 280, 313, 43);

        jLabel18.setBackground(new java.awt.Color(51, 255, 0));
        jLabel18.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 102, 102));
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/Coin-icon.png"))); // NOI18N
        jLabel18.setText("20");
        jPanel5.add(jLabel18);
        jLabel18.setBounds(150, 250, 39, 20);

        jLabel20.setBackground(new java.awt.Color(51, 255, 0));
        jLabel20.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 255, 204));
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/Coin-icon.png"))); // NOI18N
        jLabel20.setText("25.00");
        jPanel5.add(jLabel20);
        jLabel20.setBounds(1120, 240, 64, 23);

        jLabel21.setBackground(new java.awt.Color(51, 255, 0));
        jLabel21.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 102, 102));
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/Coin-icon.png"))); // NOI18N
        jLabel21.setText("22.00");
        jPanel5.add(jLabel21);
        jLabel21.setBounds(450, 250, 63, 23);

        jLabel22.setBackground(new java.awt.Color(51, 255, 0));
        jLabel22.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 204, 153));
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/Coin-icon.png"))); // NOI18N
        jLabel22.setText("18.00");
        jPanel5.add(jLabel22);
        jLabel22.setBounds(790, 250, 64, 23);

        jButton25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/plus.png"))); // NOI18N
        jButton25.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton25);
        jButton25.setBounds(340, 40, 30, 30);

        jButton26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/minus.png"))); // NOI18N
        jButton26.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton26);
        jButton26.setBounds(340, 120, 30, 30);

        jButton27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/minus.png"))); // NOI18N
        jButton27.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton27);
        jButton27.setBounds(670, 120, 30, 30);

        jButton28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/plus.png"))); // NOI18N
        jButton28.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton28ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton28);
        jButton28.setBounds(670, 40, 30, 30);

        jButton29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/minus.png"))); // NOI18N
        jButton29.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton29ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton29);
        jButton29.setBounds(990, 110, 30, 30);

        jButton30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/plus.png"))); // NOI18N
        jButton30.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton30ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton30);
        jButton30.setBounds(990, 30, 30, 30);

        jButton22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/plus.png"))); // NOI18N
        jButton22.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton22);
        jButton22.setBounds(10, 40, 30, 30);

        jButton21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/minus.png"))); // NOI18N
        jButton21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton21);
        jButton21.setBounds(10, 120, 30, 30);

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/temp1.jpg"))); // NOI18N
        jPanel5.add(jLabel27);
        jLabel27.setBounds(0, 0, 1340, 340);

        jPanel1.add(jPanel5);
        jPanel5.setBounds(20, 630, 1330, 339);

        jLabel12.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 0, 51));
        jLabel12.setText("Today,s Intelligent Food Quote:");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(490, 170, 222, 38);

        jLabel13.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(153, 0, 153));
        jLabel13.setText("“If you’re afraid of butter, use cream.”");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(730, 180, 235, 17);

        jPanel6.setLayout(null);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/rabri-recipe.jpg"))); // NOI18N
        jPanel6.add(jLabel14);
        jLabel14.setBounds(20, 330, 267, 200);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/chikoo-kulfi.jpg"))); // NOI18N
        jPanel6.add(jLabel15);
        jLabel15.setBounds(22, 46, 260, 200);

        o1.setEditable(false);
        o1.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        o1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        o1.setText("0");
        jPanel6.add(o1);
        o1.setBounds(130, 10, 30, 30);

        o2.setEditable(false);
        o2.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        o2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        o2.setText("0");
        jPanel6.add(o2);
        o2.setBounds(130, 300, 30, 30);

        jButton8.setBackground(new java.awt.Color(255, 255, 153));
        jButton8.setFont(new java.awt.Font("Vivaldi", 1, 24)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 0, 0));
        jButton8.setText("Rabri-e-fruto");
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton8);
        jButton8.setBounds(130, 540, 149, 39);

        jButton13.setBackground(new java.awt.Color(255, 255, 153));
        jButton13.setFont(new java.awt.Font("Vivaldi", 1, 24)); // NOI18N
        jButton13.setForeground(new java.awt.Color(255, 0, 0));
        jButton13.setText("Befikre Kulfi");
        jButton13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton13);
        jButton13.setBounds(111, 253, 171, 39);

        jLabel23.setBackground(new java.awt.Color(51, 255, 0));
        jLabel23.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 102, 102));
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/Coin-icon.png"))); // NOI18N
        jLabel23.setText("05.00");
        jPanel6.add(jLabel23);
        jLabel23.setBounds(32, 263, 67, 23);

        jLabel24.setBackground(new java.awt.Color(51, 255, 0));
        jLabel24.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 102, 102));
        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/Coin-icon.png"))); // NOI18N
        jLabel24.setText("08.00");
        jPanel6.add(jLabel24);
        jLabel24.setBounds(50, 550, 68, 23);

        jButton31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/plus.png"))); // NOI18N
        jButton31.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton31ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton31);
        jButton31.setBounds(170, 300, 30, 30);

        jButton32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/minus.png"))); // NOI18N
        jButton32.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton32ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton32);
        jButton32.setBounds(90, 300, 30, 30);

        jButton23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/plus.png"))); // NOI18N
        jButton23.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton23);
        jButton23.setBounds(170, 10, 30, 30);

        jButton24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/minus.png"))); // NOI18N
        jButton24.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton24);
        jButton24.setBounds(90, 10, 30, 30);

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/temp1.jpg"))); // NOI18N
        jPanel6.add(jLabel28);
        jLabel28.setBounds(0, 0, 310, 590);

        jPanel1.add(jPanel6);
        jPanel6.setBounds(1360, 270, 310, 590);

        jButton4.setBackground(new java.awt.Color(153, 255, 204));
        jButton4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/checkout.png"))); // NOI18N
        jButton4.setText("CheckOut");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(1430, 890, 174, 70);

        jButton14.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/logout.png"))); // NOI18N
        jButton14.setText("Log Out");
        jButton14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton14);
        jButton14.setBounds(1540, 110, 111, 40);

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/temp.jpg"))); // NOI18N
        jPanel1.add(jLabel25);
        jLabel25.setBounds(0, 0, 1680, 990);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1676, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 987, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1694, 1034));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
int n = Integer.parseInt(r1.getText());
  n++;
  r1.setText(""+n);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
int n = Integer.parseInt(r3.getText());
  n++;
  r3.setText(""+n);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
int n = Integer.parseInt(r2.getText());
  n++;
  r2.setText(""+n);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
int n = Integer.parseInt(o2.getText());
  n++;
  o2.setText(""+n);          // TODO add your handling code here:
             // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
int n = Integer.parseInt(s4.getText());
  n++;
  s4.setText(""+n);          // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
int n = Integer.parseInt(s1.getText());
  n++;
  s1.setText(""+n);          // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
int n = Integer.parseInt(s3.getText());
  n++;
  s3.setText(""+n);          // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
int n = Integer.parseInt(s2.getText());
  n++;
  s2.setText(""+n);          // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
int n = Integer.parseInt(o1.getText());
  n++;
  o1.setText(""+n);          // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
double regular,special,others,amount=0.0;

regular = Double.parseDouble(r1.getText())*11.00 + Double.parseDouble(r2.getText())*15.00 + Double.parseDouble(r3.getText())*19.99 ; 
special = Double.parseDouble(s1.getText())*22.00 + Double.parseDouble(s2.getText())*22.00 + Double.parseDouble(s3.getText())*18.00 + Double.parseDouble(s4.getText())*25.00 ; 
others = Double.parseDouble(o1.getText())*5.00 + Double.parseDouble(o2.getText())*8.00  ; 
amount = regular + special + others;
amount = amount*100; //  Rounding amount upto 2 decimal places
amount = Math.round(amount);
amount = amount /100;  
System.out.println(""+amount);
/////////////////--------------------------------
if(Double.parseDouble(balance.getText())>=amount && amount!=0.0)
{
  try{
            Class.forName("java.sql.Driver");
            String database = "jdbc:mysql://localhost:3306/foodforintelligents";
            Connection conn = DriverManager.getConnection(database, "root","");
            Statement stmt = conn.createStatement();
           // String sql = "update menu set order_amount = " + amount + "where username = '" + usernamemenu.getText() + "';";
           // stmt.executeUpdate(sql);     
            //sql = "update menu set balance = " + (Double.parseDouble(balance.getText())-amount) + "where username = '" + usernamemenu.getText() + "';";
           // stmt.executeUpdate(sql);  
            
            checkout ch = new checkout();
            Random rand = new Random();
            int num = rand.nextInt(9000) + 1000;  
            ch.orderidcheckout.setText(usernamemenu.getText().substring(0, 1)+num);
            ch.amountcheckout.setText(""+amount);
            ch.usernamecheckout.setText(usernamemenu.getText());
            String sql = "select * from login where username = '" + usernamemenu.getText() + "';" ;
            ResultSet rs = stmt.executeQuery(sql);
             if(rs.next())
             {
                 String s;
                 s = rs.getString("phone");
                 ch.phonecheckout.setText(s);
             }
             else
                 System.out.println("Database error in retriving the phone number and setting to the Checkout");
            ch.setVisible(true);
            this.setVisible(false);
            
            }
     catch(Exception e)
        {
          System.out.println("Not Connected, Error:  "+e.getMessage());
        }
}
else if(amount==0.0)
{
     JOptionPane.showMessageDialog(null,"Please select atleast a single item.","",JOptionPane.WARNING_MESSAGE);
}
else
{
    JOptionPane.showMessageDialog(null,"Your Order amount is more than your Current balance.","",JOptionPane.WARNING_MESSAGE);
}
   
//---------------------------------

// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
feedback f = new feedback();
f.setVisible(true);
f.usernamefeedback.setText(this.usernamemenu.getText());
this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
orderStatus os = new orderStatus();
os.profileusername.setText(usernamemenu.getText());
//------------------------------
  try{
             Class.forName("java.sql.Driver");
            String database = "jdbc:mysql://localhost:3306/foodforintelligents";
            Connection conn = DriverManager.getConnection(database, "root","");
            Statement stmt = conn.createStatement();
             String sql = "select * from login where username = '" + usernamemenu.getText() + "';" ;
             ResultSet rs = stmt.executeQuery(sql);
             if(rs.next())
             {
                 String s;
                 s = rs.getString("name");
                 os.profilename.setText(""+s); 
                 s = rs.getString("phone");
                 os.profilephone.setText(""+s); 
                 s = rs.getString("email");
                 os.profileemail.setText(""+s); 
             }
             else
                 System.out.println("Sorry Error occured");
             
             //*************************
             sql = "select * from menu where username = '" + usernamemenu.getText() + "';" ;
             rs = stmt.executeQuery(sql);
             if(rs.next())
             {
                 String s,date,orderid,orderamount;
                 s = rs.getString("purchaseid");
                 os.orderidorderstatus.setText(""+s); 
                 date = rs.getString("order_time");
                 os.ordertimeorderstatus.setText(""+date);
                 if(date.equalsIgnoreCase("No Recent Order"))
                 { os.presentstatusprofile.setText("No Recent Order"); }else
                 { os.presentstatusprofile.setText("Order Placed"); }
                 orderid = rs.getString("purchaseid");
                 os.orderidorderstatus.setText(""+orderid);
                 orderamount = rs.getString("order_amount");
                 os.orderamountorderstatus.setText(""+orderamount);
                /* s = rs.getString("phone");
                 os.profilephone.setText(""+s); 
                 s = rs.getString("email");
                 os.profileemail.setText(""+s); */
             }
             else
                 System.out.println("Sorry Error occured");
             
             //******************************* 
            }
     catch(Exception e)
     {
               System.out.println("Not Connected, Error:  "+e.getMessage());
     }
//-------------------------------
os.setVisible(true);
this.setVisible(false);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
question q = new question();
q.usernamequestions.setText(usernamemenu.getText());
q.setVisible(true);
this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
login l = new login();
l.setVisible(true);
this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
int n = Integer.parseInt(r1.getText());
if(n!=0)
  n--;
  r1.setText(""+n);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
int n = Integer.parseInt(r2.getText());
if(n!=0)
  n--;
  r2.setText(""+n);         // TODO add your handling code here:
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
int n = Integer.parseInt(r3.getText());
if(n!=0)
  n--;
  r3.setText(""+n);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
int n = Integer.parseInt(s1.getText());
if(n!=0)
  n--;
  s1.setText(""+n);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
int n = Integer.parseInt(o1.getText());
if(n!=0)
  n--;
  o1.setText(""+n);          // TODO add your handling code here:
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
int n = Integer.parseInt(s2.getText());
if(n!=0)
  n--;
  s2.setText(""+n);          // TODO add your handling code here:
    }//GEN-LAST:event_jButton26ActionPerformed

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
int n = Integer.parseInt(s3.getText());
if(n!=0)
  n--;
  s3.setText(""+n);            // TODO add your handling code here:
    }//GEN-LAST:event_jButton27ActionPerformed

    private void jButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton29ActionPerformed
int n = Integer.parseInt(s4.getText());
if(n!=0)
  n--;
  s4.setText(""+n);          // TODO add your handling code here:
    }//GEN-LAST:event_jButton29ActionPerformed

    private void jButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton32ActionPerformed
int n = Integer.parseInt(o2.getText());
if(n!=0)
  n--;
  o2.setText(""+n);         // TODO add your handling code here:
    }//GEN-LAST:event_jButton32ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
int n = Integer.parseInt(r1.getText());
  n++;
  r1.setText(""+n);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
int n = Integer.parseInt(r2.getText());
  n++;
  r2.setText(""+n);         // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
int n = Integer.parseInt(r3.getText());
  n++;
  r3.setText(""+n);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
int n = Integer.parseInt(s1.getText());
  n++;
  s1.setText(""+n);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
int n = Integer.parseInt(s2.getText());
  n++;
  s2.setText(""+n);          // TODO add your handling code here:
    }//GEN-LAST:event_jButton25ActionPerformed

    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
int n = Integer.parseInt(s3.getText());
  n++;
  s3.setText(""+n);            // TODO add your handling code here:
    }//GEN-LAST:event_jButton28ActionPerformed

    private void jButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton30ActionPerformed
int n = Integer.parseInt(s4.getText());
  n++;
  s4.setText(""+n);          // TODO add your handling code here:
    }//GEN-LAST:event_jButton30ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
int n = Integer.parseInt(o1.getText());
  n++;
  o1.setText(""+n);          // TODO add your handling code here:
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton31ActionPerformed
int n = Integer.parseInt(o2.getText());
  n++;
  o2.setText(""+n);         // TODO add your handling code here:
    }//GEN-LAST:event_jButton31ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel balance;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField o1;
    private javax.swing.JTextField o2;
    private javax.swing.JTextField r1;
    private javax.swing.JTextField r2;
    private javax.swing.JTextField r3;
    private javax.swing.JTextField s1;
    private javax.swing.JTextField s2;
    private javax.swing.JTextField s3;
    private javax.swing.JTextField s4;
    public static javax.swing.JLabel usernamemenu;
    // End of variables declaration//GEN-END:variables
}
