

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Saurabh Shubham
 */
public class orderStatus extends javax.swing.JFrame {

    /**
     * Creates new form orderStatus
     */
    public orderStatus() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        profilename = new javax.swing.JLabel();
        profilephone = new javax.swing.JLabel();
        profileemail = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        orderidorderstatus = new javax.swing.JLabel();
        orderamountorderstatus = new javax.swing.JLabel();
        presentstatusprofile = new javax.swing.JLabel();
        ordertimeorderstatus = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        profileusername = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/logo.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(280, 30, 400, 91);

        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel3.setText("Name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 11, 44, 21);

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel7.setText("Phone number");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(30, 56, 116, 21);

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel6.setText("Email");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 104, 43, 21);

        profilename.setBackground(new java.awt.Color(153, 255, 153));
        profilename.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        profilename.setForeground(new java.awt.Color(51, 0, 51));
        profilename.setText("Nothing");
        jPanel1.add(profilename);
        profilename.setBounds(185, 7, 272, 30);

        profilephone.setBackground(new java.awt.Color(153, 255, 153));
        profilephone.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        profilephone.setForeground(new java.awt.Color(51, 0, 51));
        profilephone.setText("Nothing");
        jPanel1.add(profilephone);
        profilephone.setBounds(185, 52, 272, 30);

        profileemail.setBackground(new java.awt.Color(153, 255, 153));
        profileemail.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        profileemail.setForeground(new java.awt.Color(51, 0, 51));
        profileemail.setText("Nothing");
        jPanel1.add(profileemail);
        profileemail.setBounds(185, 100, 272, 30);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/2.jpg"))); // NOI18N
        jPanel1.add(jLabel15);
        jLabel15.setBounds(0, 0, 500, 140);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(189, 233, 500, 140);

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel2.setText("Your Profile:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(290, 190, 103, 30);

        jPanel2.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel4.setText("Last Order Status: ");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(20, 26, 149, 21);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 51));
        jLabel5.setText("Order ID: ");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(186, 54, 75, 25);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 51));
        jLabel8.setText("Order Amount:");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(450, 40, 109, 40);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 51));
        jLabel9.setText("Present Status: ");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(186, 97, 129, 28);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 51, 51));
        jLabel10.setText("Order Time: ");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(33, 151, 93, 19);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 51, 51));
        jLabel12.setText("Expected:");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(485, 146, 73, 28);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 51, 0));
        jLabel13.setText("30 minutes from order time.");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(576, 146, 172, 29);

        orderidorderstatus.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(orderidorderstatus);
        orderidorderstatus.setBounds(279, 51, 160, 28);

        orderamountorderstatus.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        orderamountorderstatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/Coin-icon.png"))); // NOI18N
        orderamountorderstatus.setText("0.00");
        jPanel2.add(orderamountorderstatus);
        orderamountorderstatus.setBounds(582, 45, 160, 28);

        presentstatusprofile.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(presentstatusprofile);
        presentstatusprofile.setBounds(333, 97, 235, 28);

        ordertimeorderstatus.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ordertimeorderstatus.setForeground(new java.awt.Color(153, 0, 51));
        ordertimeorderstatus.setText("No Recent Order");
        jPanel2.add(ordertimeorderstatus);
        ordertimeorderstatus.setBounds(153, 146, 310, 28);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/2.jpg"))); // NOI18N
        jLabel16.setText("jLabel16");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(0, 0, 760, 210);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(90, 390, 760, 210);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/place.png"))); // NOI18N
        jButton1.setText("OK");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(410, 610, 100, 40);

        jLabel11.setBackground(new java.awt.Color(204, 0, 0));
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Personal Information:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(40, 150, 230, 30);

        profileusername.setBackground(new java.awt.Color(153, 255, 153));
        profileusername.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        profileusername.setForeground(new java.awt.Color(51, 0, 102));
        profileusername.setText("Nothing");
        getContentPane().add(profileusername);
        profileusername.setBounds(410, 190, 215, 30);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/free-wallpaper-food-6-high-resolution-wallpaper.jpg"))); // NOI18N
        getContentPane().add(jLabel14);
        jLabel14.setBounds(0, 0, 930, 670);

        setSize(new java.awt.Dimension(930, 707));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    menu m = new menu();
    m.usernamemenu.setText(profileusername.getText());
      try{
            Class.forName("java.sql.Driver");
            String database = "jdbc:mysql://localhost:3306/foodforintelligents";
            Connection conn = DriverManager.getConnection(database, "root","");
            Statement stmt = conn.createStatement();
             String sql = "select balance from menu where username = '" + profileusername.getText() + "';" ;
             ResultSet rs = stmt.executeQuery(sql);
             if(rs.next())
             {
                 String s;
                 s = rs.getString("balance");
                 m.balance.setText(s);
             }
              
            }
            catch(Exception e)
            {
               System.out.println("Not Connected, Error:  "+e.getMessage());
            }
    
    m.setVisible(true);
    this.setVisible(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(orderStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(orderStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(orderStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(orderStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new orderStatus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JLabel orderamountorderstatus;
    public static javax.swing.JLabel orderidorderstatus;
    public static javax.swing.JLabel ordertimeorderstatus;
    public static javax.swing.JLabel presentstatusprofile;
    public static javax.swing.JLabel profileemail;
    public static javax.swing.JLabel profilename;
    public static javax.swing.JLabel profilephone;
    public static javax.swing.JLabel profileusername;
    // End of variables declaration//GEN-END:variables
}
